title: My Learnings and Blog
author: Niranjan Sai
description: >-
  Welcome to my technical blog—a space where I document my learnings, share insights, and post detailed notes on everything from Linux internals and system design to Kubernetes, containers, security, and more. As I continue growing in my journey, I’ll also be expanding into other areas of tech, capturing my progress and discoveries along the way.

baseurl: ""          # subpath of your site, e.g., /blog
url: "https://kvnsai.github.io" # base hostname

# Use remote_theme for GitHub Pages
remote_theme: "mmistakes/minimal-mistakes@4.27"

markdown: kramdown
kramdown:
  toc_levels: 1..3

plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - index.markdown
